---

- hosts: minio_server
  become: yes
  tasks:
  - name: Ensures dir exists
    file: path=/mnt/data-01/minio state=directory    
  - name: start minio docker
    docker_container:
      name: minio
      image: minio/minio
      pull: yes
      networks:
        - name: lacmus_server
      networks_cli_compatible: yes
      command: server /data
      state: started
      mounts:
        -
          source: /mnt/data-01/minio
          target: /data
          type: bind 
      exposed_ports:
        - "9000:9000"
      env:
        MINIO_ROOT_USER: "{{ lookup('env','MINIO_ROOT_USER') }}"
        MINIO_ROOT_PASSWORD: "{{ lookup('env','MINIO_ROOT_PASSWORD') }}"
      detach: true
      tty: true