---

- hosts: minio_server
  become: yes
  tasks:
  - name: Ensures dir exists
    file: path=/media/data/minio state=directory    
  - name: start minio docker
    docker_container:
      name: minio
      image: minio/minio
      pull: yes
      command: server /data
      state: started
      mounts:
        -
          source: /media/data/minio
          target: /data
          type: bind 
      published_ports:
        127.0.0.1:9000:9000
      env:
        MINIO_ACCESS_KEY: "{{ lookup('env','MINIO_ACCESS_KEY') }}"
        MINIO_SECRET_KEY: "{{ lookup('env','MINIO_SECRET_KEY') }}"
      detach: true
      tty: true